name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-lfn71dyu72rpt33w.cn-beijing.personal.cr.aliyuncs.com
        username: diandiantmd
        password: zhang666999
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/arm64v8/postgres:12-bullseye docker://crpi-lfn71dyu72rpt33w.cn-beijing.personal.cr.aliyuncs.com/zhangyiwen91/arm64v8/postgres:12-bullseye
         
         
         
